### ISSUE TITLE
Shortcut `-s` results in `opt:stage` variable set

### ISSUE THREAD

**Issue by jazen** [vkkis93/serverless-step-functions-offline#12]
```
provider:
  stage: ${opt:stage, 'dev'}
```

Running

```
sls step-functions-offline -s Foo
```

sets `opt:stage` to `Foo` and therefore the default value `dev` isn't used. Using long form `--stateMachine=Foo` works as expected.

Maybe removing the short form is the best solution to avoid clashes with `serverless` itself?

**Comment by vkkis93** [comment]
Released with `2.0.1`
