### ISSUE TITLE
Absolut path for Event file

### ISSUE THREAD

**Issue by mataide** [vkkis93/serverless-step-functions-offline#15]
Absolut path for event file doesnt work.

Ex:

`sls step-functions-offline --stateMachine=TournamentMachine --event=/Users/marcusataide/Documents/Workspace/proak-workflow/proak-workflow/api/tournament/status/registering/event.json`

But if you provide a path like this, works:

`sls step-functions-offline --stateMachine=TournamentMachine --event=./api/tournament/status/registering/event.json`

**Comment by vkkis93** [comment]
Hi @mataide .
Thank you for interest in my plugin and sorry for long response.
I fixed and it will be released in package v2.1.0.

**Comment by vkkis93** [comment]
Hi @mataide .
Fixed in 2.1.0
