### ISSUE TITLE
Choice variables can only be one level deep.

### ISSUE THREAD

**Issue by brianeletype** [vkkis93/serverless-step-functions-offline#17]
If you're creating a Choice type state and the variable is in a child object, the variable will be undefined.

For example, assume you have data going into your choice that looks like `{myBoolean: true, myObject: {objBoolean: true}}`. 

If you have your choice variable value set to `$.myBoolean` it will work and the choice, true, will be evaluated.

If you have your choice variable set to `$.myObject.objBoolean`, the value will be undefined and it will not evaluate to true.

This is due to the way that the values are retrieved out of the state here: https://github.com/vkkis93/serverless-step-functions-offline/blob/e2ffc7707e0d2b41d70c55bcddba99e83c0c6acf/build.js#L215

In our example above, we'll be attempting to pull `result['myObject.objBoolean']` which is not the same as `result.myObject.objBoolean`.   We'll need to come up with a better way of evaluating the `result` objects properties other than just straight array lookup.

**Comment by vkkis93** [comment]
Hi @brianeletype .
Fix will be released in v2.2.0.
I will write here when I publish version

**Comment by vkkis93** [comment]
Released in v2.1.2
