### ISSUE TITLE
Published version on NPM doesn't seems to be the same as the one in the repo

### ISSUE THREAD

**Issue by j0k3r** [vkkis93/serverless-step-functions-offline#2]
I found few changes in the NPM version which aren't in the repo.
It might be a good practice to keep them synced. At least if you don't want to deal with conflicts when you'll merge PR from contributors.

Also, it might be a good practice to create a release on GitHub (or a tag) each time you release a new version of your plugin.

**Comment by vkkis93** [comment]
Hi @j0k3r.
Totally agree with about `create a release on GitHub (or a tag) each time you release a new version of your plugin.` For future changes I will create release/tag.
About local changes - all next changes will be synced with github.
