### ISSUE TITLE
Compatibility with serverless-webpack

### ISSUE THREAD

**Issue by j0k3r** [vkkis93/serverless-step-functions-offline#3]
All my Lambda are written in ES6 and I use [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) to build them and be able to run them on AWS Lambda.

Your plugin doesn't seems to be compatible with it.
When the step function start I got an error which means the js isn't compiled before being executed:

```
Serverless: Building StepWorkFlow
OOPS /home/projectsrc/schedule-content/index.js:1
(function (exports, require, module, __filename, __dirname) { import { ScheduleContent } from './scheduleContent'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
```

**Comment by vkkis93** [comment]
yes, currently *serverless-step-functions-offline* does not work with plugins. I will look at this problem

**Comment by vkkis93** [comment]
Hi @j0k3r,
Did plugin **serverless-step-functions-offline**  last in the list of your plugins ?

**Comment by vkkis93** [comment]
Hi @j0k3r , currently I work with that.
I hope next week it will be done

**Comment by j0k3r** [comment]
Great, don't hesitate to ping. I've a project available to test it!

**Comment by ajagnanan** [comment]
Just fyi, a workaround for now is referencing the compiled index.js directly, something like this should work:
```
stepFunctionsOffline:
    FirstState: .webpack/service/index.func1
    FinalState: .webpack/service/index.func2
```

**Comment by vkkis93** [comment]
Hi @j0k3r .
I have done this feature on my side
But I'm waiting when my [PR](https://github.com/serverless-heaven/serverless-webpack/pull/313) will be merged. Only after that we will have compatibility with serverless-webpack

**Comment by vkkis93** [comment]
BTW, I did not write documentation about usage
I will write when serverless-webpack will be released with my PR

**Comment by vkkis93** [comment]
I updated [documentation](https://github.com/vkkis93/serverless-step-functions-offline#usage-with-serverless-webpack).

@j0k3r, can I close this issue ?
Did you try it ?

**Comment by j0k3r** [comment]
I'll try it soon.
Meanwhile I'll close the issue and open a new one if I got some problem.
Good job fixing that issue 👍
