### ISSUE TITLE
Fix vulnerability in lodash

### ISSUE THREAD

**Issue by lukemcgregor** [vkkis93/serverless-step-functions-offline#36]
Report: https://snyk.io/test/github/vkkis93/serverless-step-functions-offline?targetFile=package.json

Resolution: lodash 4.17.11 -> 4.17.12

**Comment by lukemcgregor** [comment]
Fixed by #37

**Comment by vkkis93** [comment]
Hi @lukemcgregor 
Going to fix it in a few days

**Comment by vkkis93** [comment]
fixed
